### ISSUE TITLE
Error in prec_meandiff()?

### ISSUE THREAD

**Issue by clayford** [CTU-Bern/presize#106]
The function prec_meandiff(), in differences.R, has an expression called "md" where s is calculated with denominator n1 + n2 + 2 (line 98). Shouldn't that be n1 + n2 - 2?

Thanks,
Clay Ford

**Comment by aghaynes** [comment]
Thanks for highlighting this @clayford! We'll get on it and push a fix to CRAN ASAP

**Comment by aghaynes** [comment]
a new version was submitted to CRAN yesterday and binaries have started to appear there
