### ISSUE TITLE
pre_riskratio lwr limit setting

### ISSUE THREAD

**Issue by piaclarapafundi** [CTU-Bern/presize#108]
Hi I need to extract sample size and rr possibilities which return a lwr >2.
How can I set this lwr in prec_riskratio?

Thank for your support
Pia

**Comment by aghaynes** [comment]
Hi Pia,
This isn't currently supported in the package. It's probably more of a case for `power.prop.test` or the `pwr` package (calculate the proportion of events in the comparitor group that would be consistent with a lower CI of 2 and use a one-sided test).
Hope that helps!
