### ISSUE TITLE
Improve community guidelines

### ISSUE THREAD

**Issue by TomKellyGenetics** [CTU-Bern/presize#67]
## Review: Community guidelines

_Part of [review for JOSS](https://github.com/openjournals/joss-reviews/issues/3118)._

### Contributing guidelines

Regarding this criteria, the [Contributing guidleines](https://github.com/CTU-Bern/presize/blob/master/CONTRIBUTING.md) are available (as requested in https://github.com/CTU-Bern/presize/issues/61).
 > 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

However, efforts should be made to direct users to these and guide new users through this process (I note some have been made already). 

- [x] provide contributing guidelines
- [x] direct users to them in the README
- [x]  direct users to the GitHub repository from CRAN (DESCRIPTION)
- [x] direct users to the Issues for Bug Reports from CRAN (DESCRIPTION) 
- [x] GitHub issues template for bug reports and feature requests
- [x] GitHub pull request template

Some of these are not strictly necessary for publication but are minor efforts that aid novice R users for bug reporting or seeking support via GitHub. See the [community](https://github.com/CTU-Bern/presize/community) GitHub page for further recommendations.

**Comment by aghaynes** [comment]
Thanks @TomKellyGenetics.

I've added issue templates (already in the main fork) and a PR template (in PR #61) and added a link on the readme to the contributing md file (also in PR #61).

Thanks also for pointing out the community page... I'd not noticed that...

**Comment by aghaynes** [comment]
@TomKellyGenetics, I've merged #61. Documentation typically takes about 10 mins to compile.

**Comment by TomKellyGenetics** [comment]
Thanks, I wasn't aware of the GitHub [Discussions](https://github.com/CTU-Bern/presize/discussions) feature, it seems  useful for engaging with the user community! Some of what you have there to discuss with the developers might be better suited to [Projects](https://github.com/CTU-Bern/presize/projects) though.

**Comment by aghaynes** [comment]
Thanks @TomKellyGenetics. 

We've only just started thinking about them, so they're there more so that we dont forget about them... i might well move some to projects when we actually start on them...
