### ISSUE TITLE
Reporting error: sensitivity and specificity in shiny app

### ISSUE THREAD

**Issue by TomKellyGenetics** [CTU-Bern/presize#72]
**Describe the bug**
Shiny app () returns error as shown:

```ntot' required when 'prev' is specified```

**To Reproduce**
See screenshots. Hosted locally with:

```
launch_presize_app()
```

Development version installed with `remotes::install_github("aghaynes/presize")`. Commit: https://github.com/aghaynes/presize/commit/a917c32fc886dfd2f8eee9f7c6743f2803134cf8

**Expected behavior**
Prevalence input is required by ShinyApp. It is possible to use a button to disable it. Slider could be removed from UI with conditional input.

Estimating sample size from `conf.width` without specifying `n` is not currently supported in Shiny App. Cannot specify `ntot` from Shiny App.

**Screenshots**

![Screen Shot 2021-04-07 at 15 05 15](https://user-images.githubusercontent.com/5493325/113818999-a3530800-97b3-11eb-81f7-96e8a5a2d5ee.png)
![Screen Shot 2021-04-07 at 15 05 30](https://user-images.githubusercontent.com/5493325/113819009-a64df880-97b3-11eb-8303-296f9b84efc4.png)

**Desktop (please complete the following information):**

```
R version 4.0.3 (2020-10-10)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
```

```
   presize        * 0.2.2      2021-04-07 [1] Github (aghaynes/presize@a917c32)
```

**Comment by TomKellyGenetics** [comment]
As a note on the Shiny App. The locale issue discussed in #61 seems to be resolved now. The Shiny App launches in various locale settings and I cannot reproduce the error (possibly caused by dependencies).

```
> Sys.setenv(LANG = "fr")
> 2 = x
Error in 2 = x : membre gauche de l'assignation (do_set) incorrect

> presize::launch_presize_app()

Listening on http://127.0.0.1:6747

> Sys.setenv(LANG = "ja")
> 2  + x
 エラー:  オブジェクト 'x' がありません 

> presize::launch_presize_app()

Listening on http://127.0.0.1:6747


> Sys.setenv(LANG = "")
> presize::launch_presize_app()

Listening on http://127.0.0.1:6747



> Sys.setenv(LANG = "en")
> 2 + x
Error: object 'x' not found

> presize::launch_presize_app()

Listening on http://127.0.0.1:6747


> Sys.setenv(LANG = "UTF8")
> 2+ x
Error: object 'x' not found
> presize::launch_presize_app()

Listening on http://127.0.0.1:6747
```

**Comment by aghaynes** [comment]
thanks for reporting this @TomKellyGenetics, I'll make the fix... should be easy enough i think...

**Comment by TomKellyGenetics** [comment]
I've tested installing from GItHub and verified that the Shiny App now works as expected. 👍
